name: Validate IP List in Pull Request

on:
  pull_request:
    paths:
      - 'api_list.yaml'

jobs:
  validate-ip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ipaddress

      - name: Run IP validator
        id: validate
        run: |
          python ip_validator.py api_list.yaml --json-output > results.json
          cat results.json
        continue-on-error: true

      - name: Parse validation results
        id: parse
        run: |
          status=$(jq -r '.status' results.json)
          message=$(jq -r '.message' results.json)
          suggestions=$(jq -r '.suggestions | join("\n")' results.json)
          echo "status=$status" >> $GITHUB_OUTPUT
          echo "message=$message" >> $GITHUB_OUTPUT
          echo "suggestions<<EOF" >> $GITHUB_OUTPUT
          echo "$suggestions" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Comment on PR
        if: steps.validate.outcome != 'success'
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const results = JSON.parse(fs.readFileSync('results.json'));
            const suggestions = results.suggestions.join('\n- ');
            const comment = `### IP Validation Results\n\n**Status**: ${results.status}\n**Message**: ${results.message}\n\n**Suggestions**:\n- ${suggestions}`;
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: comment
            });

      - name: Set check status
        if: steps.validate.outcome != 'success'
        run: |
          echo "Validation failed: ${{ steps.parse.outputs.message }}"
          echo "${{ steps.parse.outputs.suggestions }}"
          exit 1
